Optional numeric ratings
Peer-Stevens/peer pull request #298
Opened 2022-03-03 21:50 UTC by carpenterd777

2022-03-04 13:05 UTC, aej11a requested changes

2022-03-04 13:05 UTC, aej11a commented on src/util/ratingTypes.ts
> +}
I'm confused - why would we use 3 as the default and skip over it as a number?

The default should just be `null`

2022-03-04 13:38 UTC, carpenterd777 commented
this is a bug and should be fixed in here before merging:

```tsx
if (previousRating) {
		await axios.post(`${SERVER_BASE_URL}/editRating`, request_body);
	} /* else no previous rating has been made on this place by this user */
	await axios.post(`${SERVER_BASE_URL}/addRatingtoPlace`, request_body);
```

2022-03-27 15:07 UTC, aej11a approved these changes

2022-03-27 15:07 UTC, merged