Add styling to submit ratings page
Peer-Stevens/peer pull request #302
Opened 2022-03-08 04:59 UTC by jlora23

2022-03-08 19:28 UTC, carpenterd777 requested changes
let's favor using the "X%" relative to the container rather than depending on `Dimension.get` when we can. it might not be possible everywhere, so let us know if you can't somewhere (by leaving a comment).

2022-03-08 19:28 UTC, carpenterd777 commented on src/screens/SubmitRatingScreen.tsx
> +					height: Dimensions.get("window").height * 0.4,
```suggestion
					height: "40%"
```
did you try this?

2022-03-08 19:28 UTC, carpenterd777 commented on src/screens/SubmitRatingScreen.tsx
> +					width: Dimensions.get("window").width * 0.9,
```suggestion
					width: "90%",
```

2022-03-08 19:28 UTC, carpenterd777 commented on src/screens/SubmitRatingScreen.tsx
> +		width: Dimensions.get("window").width * 0.9,
```suggestion
		width: "90%",
```

2022-03-08 19:28 UTC, carpenterd777 commented on src/screens/SubmitRatingScreen.tsx
> +		height: Dimensions.get("window").height * 0.075,
```suggestion
		width: "45%",
		height: "7.5%",
```

2022-03-08 19:28 UTC, carpenterd777 commented on src/screens/SubmitRatingScreen.tsx
> +		width: Dimensions.get("window").width * 0.5,
```suggestion
		width: "50%",
```

2022-03-08 20:33 UTC, aej11a commented
- Flip voiceover for plus and minus button
- min should be 1
- make the button text smaller with a prop for font size, make the number and title bigger
- change "Cancel" to "Go Back"
- fix checkmarks

2022-03-24 20:33 UTC, carpenterd777 approved these changes

2022-03-24 20:34 UTC, merged