Add filter box that appears above take a stroll button
Peer-Stevens/peer pull request #36
Opened 2021-10-03 19:03 UTC by carpenterd777

In addition to doing as the title says, this also adds a few more components to Peer's component library - Box and CheckBox.

2021-10-03 19:04 UTC, carpenterd777 commented
![Screenshot_20211003-150152.png](https://user-images.githubusercontent.com/21251320/135767848-44accf27-f3ba-4ae2-be39-463fbab2f3fe.png)

2021-10-04 01:22 UTC, elenirotsides requested changes
Blocking this for now until I can run this on iOS. The app crashes when I click on the filter button. The error I get in my terminal:

```
Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.

This error is located at:
    in RNCCheckbox (created by CheckBox)
    in RCTView (at View.js:34)
    in View (created by CheckBox)
    in CheckBox (created by ForwardRef(CheckBoxWithRef))
    in ForwardRef(CheckBoxWithRef) (at CheckBox.tsx:28)
    in RCTView (at View.js:34)
    in View (at CheckBox.tsx:24)
    in CheckBox (at FilterBox.tsx:31)
    in RCTView (at View.js:34)
    in View (at Box.tsx:15)
    in Box (at FilterBox.tsx:25)
    in FilterBox (at MainView.tsx:14)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:13)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:11)
    in MainView (at App.tsx:5)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog

Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.

This error is located at:
    in RNCCheckbox (created by CheckBox)
    in RCTView (at View.js:34)
    in View (created by CheckBox)
    in CheckBox (created by ForwardRef(CheckBoxWithRef))
    in ForwardRef(CheckBoxWithRef) (at CheckBox.tsx:28)
    in RCTView (at View.js:34)
    in View (at CheckBox.tsx:24)
    in CheckBox (at FilterBox.tsx:31)
    in RCTView (at View.js:34)
    in View (at Box.tsx:15)
    in Box (at FilterBox.tsx:25)
    in FilterBox (at MainView.tsx:14)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:13)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:11)
    in MainView (at App.tsx:5)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog

Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.

This error is located at:
    in RNCCheckbox (created by CheckBox)
    in RCTView (at View.js:34)
    in View (created by CheckBox)
    in CheckBox (created by ForwardRef(CheckBoxWithRef))
    in ForwardRef(CheckBoxWithRef) (at CheckBox.tsx:28)
    in RCTView (at View.js:34)
    in View (at CheckBox.tsx:24)
    in CheckBox (at FilterBox.tsx:31)
    in RCTView (at View.js:34)
    in View (at Box.tsx:15)
    in Box (at FilterBox.tsx:25)
    in FilterBox (at MainView.tsx:14)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:13)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:11)
    in MainView (at App.tsx:5)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog

Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.

This error is located at:
    in RNCCheckbox (created by CheckBox)
    in RCTView (at View.js:34)
    in View (created by CheckBox)
    in CheckBox (created by ForwardRef(CheckBoxWithRef))
    in ForwardRef(CheckBoxWithRef) (at CheckBox.tsx:28)
    in RCTView (at View.js:34)
    in View (at CheckBox.tsx:24)
    in CheckBox (at FilterBox.tsx:31)
    in RCTView (at View.js:34)
    in View (at Box.tsx:15)
    in Box (at FilterBox.tsx:25)
    in FilterBox (at MainView.tsx:14)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:13)
    in RCTView (at View.js:34)
    in View (at MainView.tsx:11)
    in MainView (at App.tsx:5)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

2021-10-06 14:04 UTC, aej11a commented on src/components/CheckBox.tsx
> +}: CheckBoxProps): JSX.Element => {
Same comment about React.FC

2021-10-06 14:04 UTC, aej11a commented on src/components/CheckBox.tsx
> +import * as CB from "@react-native-community/checkbox";
`import CB from "`

2021-10-06 14:27 UTC, carpenterd777 commented on src/components/Button.tsx
> +	style?: StyleProp<object>; // may be unsafe, but this is the type provided
eslint still doesn't like the usage of the `object` type. I'm not sure what the "actual" type that goes in the generic here is though.

2021-10-06 14:30 UTC, carpenterd777 commented on src/components/StrollButton.tsx
> +	style?: StyleProp<object>; // may be unsafe, but this is the type provided
mmm its actually not quite true anymore. the documentation lists it as being an `object`, but it also like it better when we use `StyleProp` in some way. I'll update all instances of this comment to reflect that information

2021-10-06 17:32 UTC, aej11a commented on src/components/Button.tsx
> +	iconName: image,
This can be fixed later but at this point i would just get rid of "image" entirely

2021-10-06 17:34 UTC, merged